### PR TITLE
No blynk

### PR DESCRIPTION
**Pull request by fourstix**
Remove references to Blynk in the IoT_CloudCloud ESP8266 Thing Dev code because Blynk is ending their support of the services the code uses.  Also rewrote the setup code to show all weather conditions before calling API.

### CODE REVIEW

**Comment by nseidle** [comment]
Thanks @fourstix! This is a fairly old project. I won't be able to test but am going to merge. The PR is appreciated.

**Comment by fourstix** [comment]
Oops. Wrong repository.  Closing erroneous pull request.

**Comment by fourstix** [comment]
Argh!  Sorry @nseidle you're too quick!  Please revert this pull request.. It's very different from the original Sparkfun code....

**Comment by nseidle** [comment]
Reverted.

**Pull request merged**
